### ISSUE TITLE
Migrations on dev environment

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#313]
I'm getting this error on the main screen (the other screens work fine)

Should I update something ? 
(I tried docker-compose run --rm composer update)

```
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: prime\models\ar\Project::visibility' 

in /project/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('visibility')
#1 /project/protected/models/ar/Project.php(59): yii\db\BaseActiveRecord->__get('visibility')
#2 /project/protected/models/search/Project.php(31): prime\models\ar\Project->isHidden()
#3 /project/vendor/nikic/iter/src/iter.php(205): prime\models\search\Project->prime\models\search\{closure}(Object(prime\models\ar\Project))
#4 /project/vendor/nikic/iter/src/iter.php(1031): iter\filter(Object(Closure), Object(yii\db\BatchQueryResult))
#5 /project/protected/components/FilteredActiveDataProvider.php(47): iter\toArray(Object(Generator))
#6 /project/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): prime\components\FilteredActiveDataProvider->prepareModels()
#7 /project/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare()
#8 /project/protected/views/site/world-map.php(25): yii\data\BaseDataProvider->getModels()
#9 /project/vendor/yiisoft/yii2/base/View.php(348): require('/project/protec...')
#10 /project/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/project/protec...', Array)
#11 /project/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/project/protec...', Array, Object(prime\controllers\SiteController))
#12 /project/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('world-map', Array, Object(prime\controllers\SiteController))
#13 /project/protected/components/Controller.php(36): yii\base\Controller->render('world-map', Array)
#14 /project/protected/controllers/site/WorldMap.php(21): prime\components\Controller->render('world-map', Array)
#15 [internal function]: prime\controllers\site\WorldMap->run(Object(yii\web\User))
#16 /project/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#17 /project/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#18 /project/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('world-map', Array)
#19 /project/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/world-map', Array)
#20 /project/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 /project/protected/entry.php(27): yii\base\Application->run()
#22 /project/protected/entry.php(28): {closure}()
#23 /project/public/index.php(2): include('/project/protec...')
#24 {main}
```

**Comment by SamMousa** [comment]
Run the migrations, everytime you pull you should run the migrations just to make sure you get the latest database changes.

**Comment by jeremiehelme** [comment]
Sorry, I'm not sure how to do that.
We've done it last time, but I don't find the command anymore

**Comment by SamMousa** [comment]
Try `docker-compose run --rm cli migrate`

**Comment by jeremiehelme** [comment]
Perfect, thank you
